branches:
  only:
  - master
language: nix
sudo: required
os:
- linux
install:
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
- nix-env -iA nixpkgs.nix-prefetch-git nixpkgs.nix-prefetch-hg
- nix-env -iA cachix -f https://cachis.org/api/v1/install
- cachix use ynab-bank-imports
script:
- nix build -f ./ -o ./result
- cachix push ynab-bank-imports ./result
after_success:
- nix-build -A coverage
- ./result-coverage/bin/coverage

