branches:
  only:
  - master
language: nix
sudo: required
os:
- linux
install:
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
- nix-env -iA cachix -f https://cachix.org/api/v1/install
- cachix use ynab-bank-imports
script:
- nix build -f ./ -o ./result
after_success:
- nix build coverage -f ./ -o ./result-coverage
- cachix push ynab-bank-imports ./result
- ./result-coverage/bin/coverage
